# Instance configuration

base_port: 39270
email: pavel.filipcik@psi.ch
host: localhost
license: <license>
password: <pwd>

# Lane configuration

cpu_lane: cpu-daily
cpu_highmem_lane: cpu-highmem
gpu_lane: gpu-highmem-short
gpu_highmem_lane: gpu-highmem
gpu_highmem_short_lane: gpu-highmem-short
gpu_veryhighmem_lane: gpu-node
gpu_veryhighmem_short_lane: gpu-node-short

scratch: False
models: "/data/project/bio/steinmetz/software/microtubule-processing/models/kinesin/*aligned.mrc"
